services:
  soundpad:
    build: .
    container_name: l0sts0undp4d
    restart: unless-stopped
    ports:
      - "7331:7331"
    volumes:
      - ./data:/app/data
    environment:
      - FLASK_ENV=production
